date.timezone = Europe/Madrid
display_errors = On
error_reporting = E_ALL
log_errors = On
error_log = /var/www/html/logs/php-error.log

session.save_path = "/tmp"
upload_tmp_dir = "/var/www/html/tmp"

upload_max_filesize = 256M
post_max_size = 256M
memory_limit = 256M

session.cookie_httponly = 1
session.cookie_secure = 0
session.use_strict_mode = 1

variables_order = "EGPCS"
